<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7QcqKE8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7QcqKE8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7QcqKE8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7QcqKE8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7QcqKE8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7QcqKE8',
    'container.build_id' => 'ca040013',
    'container.build_time' => 1631026802,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7QcqKE8');
